name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:
  #  - cron: '29 0 * * 1'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:

    name: Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    steps:
      # Checkout project source
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Semgrep
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-semgrep
          restore-keys: |
            ${{ runner.os }}-pip-semgrep

      - name: Run Semgrep Scan
        run: |
            semgrep scan \
            --pro \
            --config="p/security-audit" \
            --config="p/python" \
            --config="p/owasp-top-ten" \
            --sarif \
            --output="semgrep-results.sarif" \
            --error \
        env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      

      # Upload SARIF file generated in previous step
      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep-results.sarif

      # Save SARIF 
      - name: Save SARIF as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.sarif
        #Available Options:
        #  warn: Output a warning but do not fail the action
        #  error: Fail the action with an error message
        #  ignore: Do not output any warnings or errors, the action does not fail
